//! Wire-format packet types for the `etr` protocol.
//!
//! All packets are serialised with [`bincode`] and encrypted with AES-256-GCM
//! before being sent over the wire inside a 4-byte length-prefixed frame.
use serde::{Deserialize, Serialize};

/// All message types exchanged between the `etr` client and `etrs` server.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum Packet {
    // ── Handshake ──────────────────────────────────────────────────────────
    /// Sent by the client to initiate a connection or reconnect to an existing
    /// session.  `client_id` identifies the session; `client_nonce` is a
    /// 16-byte random value used to derive the session key together with the
    /// server nonce.
    ConnectRequest {
        /// Unique session identifier generated by the client at session start.
        client_id: String,
        /// Random 16-byte client-side nonce for key derivation.
        client_nonce: [u8; 16],
    },

    /// Sent by the server in response to a [`Packet::ConnectRequest`].
    /// Contains the server's 16-byte random nonce so that both sides can
    /// independently derive the same AES-256-GCM session key via HKDF.
    ConnectResponse {
        /// Random 16-byte server-side nonce for key derivation.
        server_nonce: [u8; 16],
    },

    /// Mutual authentication token exchanged after the session key has been
    /// established.  The `mac` field carries a 32-byte value (e.g. an HMAC
    /// or an AES-GCM authentication tag) that proves possession of the shared
    /// passkey without sending it in the clear.
    Auth {
        /// 32-byte authentication token.
        mac: [u8; 32],
    },

    // ── Session Synchronisation (Reconnection) ────────────────────────────
    /// Sent by the client immediately after authentication to tell the server
    /// the highest terminal-data sequence number it has successfully received.
    /// The server uses this to determine which packets need to be replayed.
    SyncRequest {
        /// Highest `seq_num` received by the client, or `0` on a fresh connect.
        last_received_seq: u64,
    },

    /// Sent by the server in reply to [`Packet::SyncRequest`].  Mirrors the
    /// server's own receive pointer so the client can discard history entries
    /// that the server no longer needs.
    SyncResponse {
        /// Highest `seq_num` received by the server.
        last_received_seq: u64,
    },

    // ── Terminal Stream / Events ──────────────────────────────────────────
    /// A chunk of raw terminal data (stdin from client → server, or PTY
    /// output from server → client).  `seq_num` is a monotonically increasing
    /// counter that allows the receiver to detect gaps and the sender to
    /// replay missing packets after a reconnect.
    TerminalData {
        /// Monotonically increasing sequence number for this data chunk.
        seq_num: u64,
        /// Raw bytes (UTF-8 terminal data or arbitrary binary PTY output).
        data: Vec<u8>,
    },

    /// Sent whenever the client's terminal window is resized so that the
    /// server can propagate the new dimensions to the PTY.
    TerminalResize {
        /// New terminal height in character rows.
        rows: u16,
        /// New terminal width in character columns.
        cols: u16,
    },

    // ── Keepalive / Control ───────────────────────────────────────────────
    /// Periodic keepalive sent by either side to prevent the 15-second idle
    /// timeout from triggering on an otherwise quiet connection.
    Heartbeat,

    /// Sent by either side to signal a clean, intentional shutdown of the
    /// session.  The receiver should exit its connection loop without
    /// attempting to reconnect.
    Disconnect,
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Serialise a packet with bincode and deserialise it back, asserting that
    /// the round-trip is lossless.  This guards against accidental breaking
    /// changes to the wire format.
    fn round_trip(packet: &Packet) -> Packet {
        let bytes = bincode::serialize(packet).expect("serialise");
        bincode::deserialize(&bytes).expect("deserialise")
    }

    #[test]
    fn test_connect_request_round_trip() {
        let p = Packet::ConnectRequest {
            client_id: "abc123".to_string(),
            client_nonce: [7u8; 16],
        };
        let rt = round_trip(&p);
        assert!(matches!(
            rt,
            Packet::ConnectRequest { ref client_id, client_nonce }
            if client_id == "abc123" && client_nonce == [7u8; 16]
        ));
    }

    #[test]
    fn test_connect_response_round_trip() {
        let p = Packet::ConnectResponse {
            server_nonce: [9u8; 16],
        };
        let rt = round_trip(&p);
        assert!(matches!(
            rt,
            Packet::ConnectResponse { server_nonce } if server_nonce == [9u8; 16]
        ));
    }

    #[test]
    fn test_auth_round_trip() {
        let p = Packet::Auth { mac: [0xABu8; 32] };
        let rt = round_trip(&p);
        assert!(matches!(rt, Packet::Auth { mac } if mac == [0xABu8; 32]));
    }

    #[test]
    fn test_sync_request_round_trip() {
        let p = Packet::SyncRequest {
            last_received_seq: 42,
        };
        let rt = round_trip(&p);
        assert!(matches!(
            rt,
            Packet::SyncRequest { last_received_seq } if last_received_seq == 42
        ));
    }

    #[test]
    fn test_sync_response_round_trip() {
        let p = Packet::SyncResponse {
            last_received_seq: 99,
        };
        let rt = round_trip(&p);
        assert!(matches!(
            rt,
            Packet::SyncResponse { last_received_seq } if last_received_seq == 99
        ));
    }

    #[test]
    fn test_terminal_data_round_trip() {
        let p = Packet::TerminalData {
            seq_num: 7,
            data: b"hello world".to_vec(),
        };
        let rt = round_trip(&p);
        assert!(matches!(
            rt,
            Packet::TerminalData { seq_num, ref data }
            if seq_num == 7 && data == b"hello world"
        ));
    }

    #[test]
    fn test_terminal_resize_round_trip() {
        let p = Packet::TerminalResize { rows: 24, cols: 80 };
        let rt = round_trip(&p);
        assert!(matches!(
            rt,
            Packet::TerminalResize { rows, cols } if rows == 24 && cols == 80
        ));
    }

    #[test]
    fn test_heartbeat_round_trip() {
        let rt = round_trip(&Packet::Heartbeat);
        assert!(matches!(rt, Packet::Heartbeat));
    }

    #[test]
    fn test_disconnect_round_trip() {
        let rt = round_trip(&Packet::Disconnect);
        assert!(matches!(rt, Packet::Disconnect));
    }
}
